In [15]:
"""导入numpy"""
import numpy as np



### 一维数组


In [22]:
day1=np.array([5,3,3,4,1,2],dtype=int)
day2=np.array([5,5,1,1,0,3],dtype=int)
print(day1)
print(day2)

[5 3 3 4 1 2]
[5 5 1 1 0 3]


In [17]:
"""全零或者全1数组"""

day3=np.ones(6,dtype=int)
day4=np.zeros(6,dtype=int)

print(day3)
print(day4)

[1 1 1 1 1 1]
[0 0 0 0 0 0]


#### 索引和切片



In [11]:
day1=np.array([5,3,3,4,1,2],dtype=int)
print(day1[-1])
print(day1[:4])

2
[5 3 3 4]


##### 一维数组的基本统计量

**有什么统计量，求和sum,求最大值max,求最小值min,求平均值mean,求中位数median,求极差ptp,求标准差std，求方差var**

In [18]:
two_day=day1+day2
dinner_time=two_day[4:]
print(np.sum(dinner_time))  #求和 

6


In [23]:
print(two_day)
print(np.mean(two_day)) #平均值
print(np.ptp(two_day)) #极差
print(np.median(two_day)) #中位数

[10  8  4  5  1  5]
5.5
9
5.0


**多维数组**

In [24]:
first_two_day=np.array([[5,3,3,4,1,2],[5,5,1,1,3,3]])
print(first_two_day)

[[5 3 3 4 1 2]
 [5 5 1 1 3 3]]


In [25]:
second_two_day=np.zeros((2,6))
thrid_two_day=np.ones((2,6))
print(second_two_day)
print(thrid_two_day)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


**多维数组的维度**

In [27]:
dim=first_two_day.ndim
print(f"维度是{dim}")

matrix_shape=first_two_day.shape
print(f"多维数组的形状是{matrix_shape}")

matrix_size=first_two_day.size
print(f"多维数组元素的个数{matrix_size}")

matrix_dtype=first_two_day.dtype
print(f"多维数组元素的类型{matrix_dtype}")

维度是2
多维数组的形状是(2, 6)
多维数组元素的个数12
多维数组元素的类型int64


**二维数组的统计量**

In [28]:
print(first_two_day)
print(np.sum(first_two_day)) #求和
print(np.max(first_two_day)) #求最大值

[[5 3 3 4 1 2]
 [5 5 1 1 3 3]]
36
5


In [ ]:
print(np.sum(first_two_day,axis=0)) #对行求和
print(np.sum(first_two_day,axis=1)) #对列求和

[10  8  4  5  4  5]
[18 18]


In [35]:
print(first_two_day[0:,-2:])

[[1 2]
 [3 3]]


**random.randin模块**

In [39]:
print(np.random.randint(1,6))
print(np.random.randint(1,6,2))
print(np.random.randint(1,6,(2,6)))

3
[5 4]
[[1 5 1 3 4 5]
 [2 2 1 3 3 3]]


**生成0-1的小数**

In [43]:
print(np.random.rand())
print(np.random.rand(2))
print(np.random.rand(2,6))

0.7192842453981138
[0.10899812 0.619859  ]
[[0.04715051 0.90946704 0.69410609 0.832103   0.15025075 0.11397986]
 [0.90998331 0.20143601 0.11496867 0.34531654 0.43020548 0.09496487]]


**arange()方法**

In [46]:
array_1=np.arange(1,10)
print(array_1)

array_2=np.arange(1,10,2)
print(array_2)

piggy_bank=0
for _ in np.arange(10,520,10):
    piggy_bank+=_
print(piggy_bank)    

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
13260


**pandas**

In [47]:
import pandas as pd



In [ ]:
#写法1
print(pd.Series([14,7,8,10],index=["拿铁","焦糖玛奇朵","可乐","华大饼"]))


拿铁       14
焦糖玛奇朵     7
可乐        8
华大饼      10
dtype: int64


In [49]:
#写法2
print(pd.Series({"拿铁":14,"焦糖玛奇朵":7,"可乐":8,"华大饼":10}))


拿铁       14
焦糖玛奇朵     7
可乐        8
华大饼      10
dtype: int64


In [51]:
shop1=pd.Series({"拿铁":14,"焦糖玛奇朵":7,"可乐":8,"华大饼":10})
shop1[0]

C:\Users\36317\AppData\Local\Temp\ipykernel_16248\1420841353.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  shop1[0]


np.int64(14)

In [52]:
shop1=pd.Series({"拿铁":14,"焦糖玛奇朵":7,"可乐":8,"华大饼":10})
shop2=pd.Series({"拿铁":20,"焦糖玛奇朵":3,"雪碧":13,"冰淇淋":6})

sum_shop=shop1.add(shop2,fill_value=0)
print(sum_shop)

冰淇淋       6.0
华大饼      10.0
可乐        8.0
拿铁       34.0
焦糖玛奇朵    10.0
雪碧       13.0
dtype: float64


**减法sub(),加法add(),除法div(),乘法mul()**