In [15]:
"""导入numpy"""
import numpy as np



### 一维数组


In [22]:
day1=np.array([5,3,3,4,1,2],dtype=int)
day2=np.array([5,5,1,1,0,3],dtype=int)
print(day1)
print(day2)

[5 3 3 4 1 2]
[5 5 1 1 0 3]


In [17]:
"""全零或者全1数组"""

day3=np.ones(6,dtype=int)
day4=np.zeros(6,dtype=int)

print(day3)
print(day4)

[1 1 1 1 1 1]
[0 0 0 0 0 0]


#### 索引和切片



In [11]:
day1=np.array([5,3,3,4,1,2],dtype=int)
print(day1[-1])
print(day1[:4])

2
[5 3 3 4]


##### 一维数组的基本统计量

**有什么统计量，求和sum,求最大值max,求最小值min,求平均值mean,求中位数median,求极差ptp,求标准差std，求方差var**

In [18]:
two_day=day1+day2
dinner_time=two_day[4:]
print(np.sum(dinner_time))  #求和 

6


In [23]:
print(two_day)
print(np.mean(two_day)) #平均值
print(np.ptp(two_day)) #极差
print(np.median(two_day)) #中位数

[10  8  4  5  1  5]
5.5
9
5.0


**多维数组**

In [24]:
first_two_day=np.array([[5,3,3,4,1,2],[5,5,1,1,3,3]])
print(first_two_day)

[[5 3 3 4 1 2]
 [5 5 1 1 3 3]]


In [25]:
second_two_day=np.zeros((2,6))
thrid_two_day=np.ones((2,6))
print(second_two_day)
print(thrid_two_day)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


**多维数组的维度**

In [27]:
dim=first_two_day.ndim
print(f"维度是{dim}")

matrix_shape=first_two_day.shape
print(f"多维数组的形状是{matrix_shape}")

matrix_size=first_two_day.size
print(f"多维数组元素的个数{matrix_size}")

matrix_dtype=first_two_day.dtype
print(f"多维数组元素的类型{matrix_dtype}")

维度是2
多维数组的形状是(2, 6)
多维数组元素的个数12
多维数组元素的类型int64


**二维数组的统计量**

In [28]:
print(first_two_day)
print(np.sum(first_two_day)) #求和
print(np.max(first_two_day)) #求最大值

[[5 3 3 4 1 2]
 [5 5 1 1 3 3]]
36
5


In [ ]:
print(np.sum(first_two_day,axis=0)) #对行求和
print(np.sum(first_two_day,axis=1)) #对列求和

[10  8  4  5  4  5]
[18 18]


In [35]:
print(first_two_day[0:,-2:])

[[1 2]
 [3 3]]


**random.randin模块**

In [39]:
print(np.random.randint(1,6))
print(np.random.randint(1,6,2))
print(np.random.randint(1,6,(2,6)))

3
[5 4]
[[1 5 1 3 4 5]
 [2 2 1 3 3 3]]


**生成0-1的小数**

In [43]:
print(np.random.rand())
print(np.random.rand(2))
print(np.random.rand(2,6))

0.7192842453981138
[0.10899812 0.619859  ]
[[0.04715051 0.90946704 0.69410609 0.832103   0.15025075 0.11397986]
 [0.90998331 0.20143601 0.11496867 0.34531654 0.43020548 0.09496487]]


**arange()方法**

In [46]:
array_1=np.arange(1,10)
print(array_1)

array_2=np.arange(1,10,2)
print(array_2)

piggy_bank=0
for _ in np.arange(10,520,10):
    piggy_bank+=_
print(piggy_bank)    

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
13260


**pandas**

In [47]:
import pandas as pd



In [ ]:
#写法1
print(pd.Series([14,7,8,10],index=["拿铁","焦糖玛奇朵","可乐","华大饼"]))


拿铁       14
焦糖玛奇朵     7
可乐        8
华大饼      10
dtype: int64


In [49]:
#写法2
print(pd.Series({"拿铁":14,"焦糖玛奇朵":7,"可乐":8,"华大饼":10}))


拿铁       14
焦糖玛奇朵     7
可乐        8
华大饼      10
dtype: int64


In [51]:
shop1=pd.Series({"拿铁":14,"焦糖玛奇朵":7,"可乐":8,"华大饼":10})
shop1[0]

C:\Users\36317\AppData\Local\Temp\ipykernel_16248\1420841353.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  shop1[0]


np.int64(14)

In [52]:
shop1=pd.Series({"拿铁":14,"焦糖玛奇朵":7,"可乐":8,"华大饼":10})
shop2=pd.Series({"拿铁":20,"焦糖玛奇朵":3,"雪碧":13,"冰淇淋":6})

sum_shop=shop1.add(shop2,fill_value=0)
print(sum_shop)

冰淇淋       6.0
华大饼      10.0
可乐        8.0
拿铁       34.0
焦糖玛奇朵    10.0
雪碧       13.0
dtype: float64


**减法sub(),加法add(),除法div(),乘法mul()**

**DataFrame数据表格**

In [53]:
shop_shanghai=pd.DataFrame({"拿铁":[14,20],"焦糖玛奇朵":[7,3],"可乐":[8,13],"华夫饼":[10,6]})
print(shop_shanghai)

   拿铁  焦糖玛奇朵  可乐  华夫饼
0  14      7   8   10
1  20      3  13    6


In [56]:
#对齐
pd.set_option('display.unicode.ambiguous_as_wide',True)
pd.set_option('display.unicode.east_asian_width',True)
shop_shanghai=pd.DataFrame({"拿铁":[14,20],"焦糖玛奇朵":[7,3],"可乐":[8,13],"华夫饼":[10,6]},index=['shop1','shop2'])
print(shop_shanghai)

       拿铁  焦糖玛奇朵  可乐  华夫饼
shop1    14           7     8      10
shop2    20           3    13       6


In [57]:
#删除行
shop_shanghai.drop('可乐',axis=1,inplace=True)
print(shop_shanghai)

       拿铁  焦糖玛奇朵  华夫饼
shop1    14           7      10
shop2    20           3       6


In [60]:
#DataFrame行的增删查改
print(shop_shanghai.loc['shop1'])

拿铁          14
焦糖玛奇朵     7
华夫饼        10
Name: shop1, dtype: int64


In [61]:
print(shop_shanghai.loc['shop1','拿铁':'焦糖玛奇朵'])


拿铁          14
焦糖玛奇朵     7
Name: shop1, dtype: int64


In [62]:
# 将csv导入
import numpy as np
import pandas as pd
demo_data="D:\\piture\\demo.csv"
data=pd.read_csv(demo_data)
print(data)


    ID    姓名  年龄    城市  分数
0    1    李明    35    北京  85.2
1    2    王芳    28    上海  92.5
2    3    张伟    45    广州  78.9
3    4  刘秀梅    22    深圳  65.7
4    5    陈刚    51    杭州  90.1
5    6    杨丽    31    南京  72.3
6    7    赵勇    40    成都  88.6
7    8    周洁    25    武汉  75.9
8    9    孙涛    48    天津  69.4
9   10  郑秀兰    38    重庆  81.7
10  11    林强    29    西安  95.0
11  12    郭静    42    苏州  70.5
12  13    马军    33    沈阳  83.2
13  14    唐红    27    青岛  67.8
14  15    徐鹏    55    长沙  91.3
15  16    宋艳    39    宁波  77.1
16  17    冯辉    24    郑州  86.4
17  18    于洋    47    济南  73.6
18  19  潘丽丽    30  哈尔滨  62.9
19  20    曾凡    43    长春  89.8
20  21    蔡霞    26    大连  79.2
21  22    杜飞    52    合肥  66.5
22  23    任静    37    福州  93.7
23  24    丁健    23  石家庄  71.0
24  25    梁爽    49    昆明  84.3
25  26    崔杰    34    无锡  68.1
26  27  姜桂兰    41    太原  96.9
27  28    贾亮    29    南昌  74.4
28  29    叶文    58    南宁  80.7
29  30    董娜    36    常州  64.0


In [63]:
print(data.head(7))
print(data.tail(4))

   ID    姓名  年龄  城市  分数
0   1    李明    35  北京  85.2
1   2    王芳    28  上海  92.5
2   3    张伟    45  广州  78.9
3   4  刘秀梅    22  深圳  65.7
4   5    陈刚    51  杭州  90.1
5   6    杨丽    31  南京  72.3
6   7    赵勇    40  成都  88.6
    ID    姓名  年龄  城市  分数
26  27  姜桂兰    41  太原  96.9
27  28    贾亮    29  南昌  74.4
28  29    叶文    58  南宁  80.7
29  30    董娜    36  常州  64.0


In [64]:
#表格的大致信息
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      30 non-null     int64  
 1   姓名      30 non-null     object 
 2   年龄      30 non-null     int64  
 3   城市      30 non-null     object 
 4   分数      30 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.3+ KB
None


In [68]:
data.sort_values('分数',ascending=False,inplace=True)
data.tail(5)

ID    姓名  年龄    城市  分数
13  14    唐红    27    青岛  67.8
21  22    杜飞    52    合肥  66.5
3    4  刘秀梅    22    深圳  65.7
29  30    董娜    36    常州  64.0
18  19  潘丽丽    30  哈尔滨  62.9

In [70]:
data[data['分数']<data['分数'].mean()]

ID    姓名  年龄    城市  分数
20  21    蔡霞    26    大连  79.2
2    3    张伟    45    广州  78.9
15  16    宋艳    39    宁波  77.1
7    8    周洁    25    武汉  75.9
27  28    贾亮    29    南昌  74.4
17  18    于洋    47    济南  73.6
5    6    杨丽    31    南京  72.3
23  24    丁健    23  石家庄  71.0
11  12    郭静    42    苏州  70.5
8    9    孙涛    48    天津  69.4
25  26    崔杰    34    无锡  68.1
13  14    唐红    27    青岛  67.8
21  22    杜飞    52    合肥  66.5
3    4  刘秀梅    22    深圳  65.7
29  30    董娜    36    常州  64.0
18  19  潘丽丽    30  哈尔滨  62.9

In [73]:
data[(data['分数']>80) & (data['分数']<90)]

ID    姓名  年龄  城市  分数
19  20    曾凡    43  长春  89.8
6    7    赵勇    40  成都  88.6
16  17    冯辉    24  郑州  86.4
0    1    李明    35  北京  85.2
24  25    梁爽    49  昆明  84.3
12  13    马军    33  沈阳  83.2
9   10  郑秀兰    38  重庆  81.7
28  29    叶文    58  南宁  80.7

In [76]:
data['水平']=pd.cut(data['分数'],bins=[60,70,80,90,100],labels=['不合格','及格','良','优秀'])
data

ID    姓名  年龄    城市  分数    水平
26  27  姜桂兰    41    太原  96.9    优秀
10  11    林强    29    西安  95.0    优秀
22  23    任静    37    福州  93.7    优秀
1    2    王芳    28    上海  92.5    优秀
14  15    徐鹏    55    长沙  91.3    优秀
4    5    陈刚    51    杭州  90.1    优秀
19  20    曾凡    43    长春  89.8      良
6    7    赵勇    40    成都  88.6      良
16  17    冯辉    24    郑州  86.4      良
0    1    李明    35    北京  85.2      良
24  25    梁爽    49    昆明  84.3      良
12  13    马军    33    沈阳  83.2      良
9   10  郑秀兰    38    重庆  81.7      良
28  29    叶文    58    南宁  80.7      良
20  21    蔡霞    26    大连  79.2    及格
2    3    张伟    45    广州  78.9    及格
15  16    宋艳    39    宁波  77.1    及格
7    8    周洁    25    武汉  75.9    及格
27  28    贾亮    29    南昌  74.4    及格
17  18    于洋    47    济南  73.6    及格
5    6    杨丽    31    南京  72.3    及格
23  24    丁健    23  石家庄  71.0    及格
11  12    郭静    42    苏州  70.5    及格
8    9    孙涛    48    天津  69.4  不合格
25  26    崔杰    34    无锡  68.1  不合格
13  14    唐红    27    青岛  67.8  不合格
21  22    杜飞    52    合肥  66.5  不合格
3    4  刘秀梅    22    深圳  65.7  不合格
29  30    董娜    36    常州  64.0  不合格
18  19  潘丽丽    30  哈尔滨  62.9  不合格